# Generated by Django 2.0 on 2018-01-05 22:27

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='password',
            field=models.CharField(default='accesscode123', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='thumb',
            field=models.FileField(upload_to='albums_thumb'),
        ),
        migrations.AlterField(
            model_name='albumimages',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='albums/thumbs'),
        ),
    ]
