# Generated by Django 2.0 on 2018-01-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_album_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=870)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
